# python3 main.py -gpuid='0, 1' \
#                     -m=0.1 \
#                     -last_layer_fixed=True \
#                     -subtractive_margin=True \
#                     -using_deform=True \
#                     -topk_k=1 \
#                     -num_prototypes=1200 \
#                     -incorrect_class_connection=-0.5 \
#                     -deformable_conv_hidden_channels=128 \
#                     -rand_seed=1

python3 main.py -gpuid='0, 1' \
                    -m=0.1 \
                    -last_layer_fixed=False \
                    -subtractive_margin=True \
                    -using_deform=True \
                    -topk_k=1 \
                    -dropout=0.0 \
                    -num_prototypes=1200 \
                    -incorrect_class_connection=-0.5 \
                    -deformable_conv_hidden_channels=128 \
                    -rand_seed=42 \
                    -num_offset_head=1 \
                    -weight_decay=0 \
                    -clip_offset=False \
                    -self_mask=False \
                    -l1=True \
                    -model_name='tune206_l1modify'